### ISSUE TITLE
UI build 

### ISSUE THREAD

**Issue by Pana** [conflux-fans/pos-pool#90]
If you have encounter this error when starting or building UI

```sh
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Users/panaw/Projects/conflux-fans/pos-pool/interface/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/panaw/Projects/conflux-fans/pos-pool/interface/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/panaw/Projects/conflux-fans/pos-pool/interface/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/panaw/Projects/conflux-fans/pos-pool/interface/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/panaw/Projects/conflux-fans/pos-pool/interface/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/panaw/Projects/conflux-fans/pos-pool/interface/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/panaw/Projects/conflux-fans/pos-pool/interface/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/panaw/Projects/conflux-fans/pos-pool/interface/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/Users/panaw/Projects/conflux-fans/pos-pool/interface/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Users/panaw/Projects/conflux-fans/pos-pool/interface/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/panaw/Projects/conflux-fans/pos-pool/interface/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/panaw/Projects/conflux-fans/pos-pool/interface/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/panaw/Projects/conflux-fans/pos-pool/interface/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/panaw/Projects/conflux-fans/pos-pool/interface/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/panaw/Projects/conflux-fans/pos-pool/interface/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/panaw/Projects/conflux-fans/pos-pool/interface/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/panaw/Projects/conflux-fans/pos-pool/interface/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.11.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Encountering the ERR_OSSL_EVP_UNSUPPORTED error during a craco build process typically indicates an issue with the version of Node.js being used in conjunction with OpenSSL. This error arises because newer versions of Node.js utilize a recent version of OpenSSL which may have deprecated certain algorithms.

To solve it, you can add the flag --openssl-legacy-provider when building your UI

eg: 

```sh
yarn start --openssl-legacy-provider 
# or
yarn build --openssl-legacy-provider 
```

**Comment by Pana** [comment]
Or you can use a lower version nodejs, eg node 16 or event lower.
